# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_GUI_CONTROL_WIDGETTYPE = descriptor.EnumDescriptor(
  name='WidgetType',
  full_name='ofxProtobufBacked.protobuf.Gui.Control.WidgetType',
  filename='WidgetType',
  values=[
    descriptor.EnumValueDescriptor(
      name='BUTTON', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TOGGLE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SLIDER', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SLIDER_2D', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SLIDER_MAP_STRING', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SLIDER_MAP_CONTENT', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='KNOB', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONTENT', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BROWSER', index=8, number=8,
      options=None,
      type=None),
  ],
  options=None,
)


_GUI_CONTROL = descriptor.Descriptor(
  name='Control',
  full_name='ofxProtobufBacked.protobuf.Gui.Control',
  filename='ofxProtobufBackedGui.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='ofxProtobufBacked.protobuf.Gui.Control.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value_type', full_name='ofxProtobufBacked.protobuf.Gui.Control.value_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='widget', full_name='ofxProtobufBacked.protobuf.Gui.Control.widget', index=2,
      number=3, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enabled', full_name='ofxProtobufBacked.protobuf.Gui.Control.enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min', full_name='ofxProtobufBacked.protobuf.Gui.Control.min', index=4,
      number=5, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max', full_name='ofxProtobufBacked.protobuf.Gui.Control.max', index=5,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _GUI_CONTROL_WIDGETTYPE,
  ],
  options=None)

_GUI = descriptor.Descriptor(
  name='Gui',
  full_name='ofxProtobufBacked.protobuf.Gui',
  filename='ofxProtobufBackedGui.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='ofxProtobufBacked.protobuf.Gui.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_id', full_name='ofxProtobufBacked.protobuf.Gui.link_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='controls', full_name='ofxProtobufBacked.protobuf.Gui.controls', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GUITREE = descriptor.Descriptor(
  name='GuiTree',
  full_name='ofxProtobufBacked.protobuf.GuiTree',
  filename='ofxProtobufBackedGui.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parent', full_name='ofxProtobufBacked.protobuf.GuiTree.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='children', full_name='ofxProtobufBacked.protobuf.GuiTree.children', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GUIGRAPH_NODE = descriptor.Descriptor(
  name='Node',
  full_name='ofxProtobufBacked.protobuf.GuiGraph.Node',
  filename='ofxProtobufBackedGui.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ofxProtobufBacked.protobuf.GuiGraph.Node.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='ofxProtobufBacked.protobuf.GuiGraph.Node.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_GUIGRAPH_EDGE = descriptor.Descriptor(
  name='Edge',
  full_name='ofxProtobufBacked.protobuf.GuiGraph.Edge',
  filename='ofxProtobufBackedGui.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ofxProtobufBacked.protobuf.GuiGraph.Edge.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to', full_name='ofxProtobufBacked.protobuf.GuiGraph.Edge.to', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='from', full_name='ofxProtobufBacked.protobuf.GuiGraph.Edge.from', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_GUIGRAPH = descriptor.Descriptor(
  name='GuiGraph',
  full_name='ofxProtobufBacked.protobuf.GuiGraph',
  filename='ofxProtobufBackedGui.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nodes', full_name='ofxProtobufBacked.protobuf.GuiGraph.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edges', full_name='ofxProtobufBacked.protobuf.GuiGraph.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import google.protobuf.descriptor_pb2

_GUI_CONTROL.fields_by_name['value_type'].enum_type = google.protobuf.descriptor_pb2._FIELDDESCRIPTORPROTO_TYPE
_GUI_CONTROL.fields_by_name['widget'].enum_type = _GUI_CONTROL_WIDGETTYPE
_GUI.fields_by_name['controls'].message_type = _GUI_CONTROL
_GUITREE.fields_by_name['parent'].message_type = _GUITREE
_GUITREE.fields_by_name['children'].message_type = _GUITREE
_GUIGRAPH.fields_by_name['nodes'].message_type = _GUIGRAPH_NODE
_GUIGRAPH.fields_by_name['edges'].message_type = _GUIGRAPH_EDGE

class Gui(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Control(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GUI_CONTROL
  DESCRIPTOR = _GUI

class GuiTree(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GUITREE

class GuiGraph(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Node(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GUIGRAPH_NODE
  
  class Edge(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GUIGRAPH_EDGE
  DESCRIPTOR = _GUIGRAPH

