#pragma once

#define	NOTIFY_FIDUCIAL_STATUS
#define	NOTIFY_FIDUCIAL_INTERSECTION
#undef	NOTIFY_FIDUCIAL_INTERSECTION_STRICT
#define	NOTIFY_FIDUCIAL_INTERSECTION_ALWAYS

#define DEFAULT_FIDUCIAL_SCALE_FACTOR ((float)1/100)

#undef	USE_FINGER_TRACKING

#ifdef NOTIFY_FIDUCIAL_STATUS
#endif

#ifdef NOTIFY_FIDUCIAL_INTERSECTION
#define MAX_INTERSECTION_DIST 1000
#endif

#define MAX_UIWEBVIEW_BROWSERS 2

#define RENDERER_GL_SMOOTHING

//#define FIDUCIAL_ANGLE_CORRECTION_DEGREES (-90)
#define FIDUCIAL_ANGLE_CORRECTION_DEGREES (0)
#define FIDUCIAL_ANGLE_CORRECTION_RADIANS (FIDUCIAL_ANGLE_CORRECTION_DEGREES*DEG_TO_RAD)

#define TRIM_RAY_PIXELS 16.0
