#pragma once

#define	NOTIFY_FIDUCIAL_STATUS
#define	NOTIFY_FIDUCIAL_INTERSECTION
#undef	NOTIFY_FIDUCIAL_INTERSECTION_STRICT
#define	NOTIFY_FIDUCIAL_INTERSECTION_ALWAYS

#undef	USE_FINGER_TRACKING

#ifdef NOTIFY_FIDUCIAL_INTERSECTION
#define MAX_INTERSECTION_DIST 1000
#endif

#define MAX_UIWEBVIEW_BROWSERS 2